name = "notsodefi-archive"
main = "index.js"
compatibility_date = "2024-01-01"

[triggers]
crons = ["0 6 * * *"]

[[kv_namespaces]]
binding = "METRICS_KV"
id = "${CF_KV_ID}"

[[r2_buckets]]
binding = "HISTORY_R2"
bucket_name = "notsodefi-history"
